#Optional Fish Installation

    - name: Change Shell to Fish
      ansible.builtin.user:
        name: greed
        shell: /usr/bin/fish
        groups: greed
        append: yes
      when: fish|bool == true

    - name: Install Fisher
      become: yes
      become_user: greed
      command: /usr/bin/fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher'
      when: fish|bool == true

    - name: Install Tide Prompt (specific to)
      become: yes
      become_user: greed
      command: /usr/bin/fish -c 'fisher install IlanCosman/tide@v5.0.1'
      when: fish|bool == true

    - name: Install Z for Fish
      become: yes
      become_user: greed
      command: /usr/bin/fish -c 'fisher install fisher install jethrokuan/z'
      when: fish|bool == true