## Alma Linux 8.5 (RHEL8)
## fish=true

- hosts: rhel
  user: greed
  become: yes
  gather_facts: yes
  tasks:
    
    - name: Set Hostname
      ansible.builtin.hostname:
        name: '{{ inventory_hostname }}'
    
    - name: Change Timezone
      community.general.timezone:
        name: America/New_York
    
    - name: Enable cockpit service 
      ansible.builtin.systemd:
        name: cockpit
        enabled: yes
        masked: no
        state: started
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '8'
    
    - name: Check if Cockpit Issue Exists
      stat:
        path: /etc/issue.d/cockpit.issue
      register: cockpit_issue_result

    - name: Check if Cockpit MOTD Exists
      stat:
        path: /etc/motd.d/cockpit
      register: cockpit_motd_result

    - name: Remove Cockpit Issue
      shell: /bin/rm -f /etc/issue.d/cockpit.issue
      when: not cockpit_issue_result.stat.exists

    - name: Remove Cockpit MOTD
      shell: /bin/rm -f /etc/motd.d/cockpit
      when: not cockpit_motd_result.stat.exists

    - name: Enable EPEL Repository on Alma 8/CentOS 8
      dnf:
        name: epel-release
        state: latest
      become: True
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '8'

    - name: Upgrade All packages
      yum:
        name: '*'
        state: latest

    - name: Install  Applications
      become: yes
      yum:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - nano
          - net-tools
          - htop
          - fish
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '8'

    - name: Change Shell to Fish
      ansible.builtin.user:
        name: greed
        shell: /usr/bin/fish
        groups: greed
        append: yes
      when: fish|bool == true

    - name: Install Fisher
      become: yes
      become_user: greed
      command: /usr/bin/fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher'
      when: fish|bool == true

    - name: Install Tide Prompt (specific to)
      become: yes
      become_user: greed
      command: /usr/bin/fish -c 'fisher install IlanCosman/tide@v5.0.1'
      when: fish|bool == true

    - name: Install Z for Fish
      become: yes
      become_user: greed
      command: /usr/bin/fish -c 'fisher install fisher install jethrokuan/z'
      when: fish|bool == true

