## Alma Linux 8.5 (RHEL8)

- import_playbook: fish.yml
  when: fish|bool == true

- hosts: rhel
  user: greed
  become: yes
  gather_facts: yes
  tasks:
    
    - name: Set Hostname
    #(example: cnaa-dev ansible_host=)
      ansible.builtin.hostname:
        name: '{{ inventory_hostname }}'
    
    - name: Change Timezone
      community.general.timezone:
        name: America/New_York
    
    - name: Enable cockpit service 
      ansible.builtin.systemd:
        name: cockpit
        enabled: yes
        masked: no
        state: started
    
    - name: Check if Cockpit Issue Exists
      stat:
        path: /etc/issue.d/cockpit.issue
      register: cockpit_issue_result

    - name: Check if Cockpit MOTD Exists
      stat:
        path: /etc/motd.d/cockpit
      register: cockpit_motd_result

    - name: Remove Cockpit Issue
      shell: /bin/rm -f /etc/issue.d/cockpit.issue
      when: not cockpit_issue_result.stat.exists

    - name: Remove Cockpit MOTD
      shell: /bin/rm -f /etc/motd.d/cockpit
      when: not cockpit_motd_result.stat.exists

    - name: Enable EPEL Repository
      dnf:
        name: epel-release
        state: latest
      become: True

    - name: Upgrade All packages
      yum:
        name: '*'
        state: latest

    - name: Install Base Applications
      become: yes
      yum:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - nano
          - net-tools
          - htop
          - fish
          - git
          - wget
          - util-linux-user

